version: "2"

services:
  db:
    image: mysql:latest #For MariaDB image mariadb:10.3.24
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      #MYSQL_ROOT_PASSWORD: #Any password test@123
    volumes:
      - db:/var/lib/mysql

  db_admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - "8080:80"

  omeka-s:
    image: sunny3p/omeka-s:latest
    # links:
    # - mysql
    restart: always
    volumes:
      - ./app:/var/www/html/files
    ports:
      - 80:80
    environment:
      user: db
      password: exampleuser
      dbname: examplepass
      host: exampledb

volumes:
  db: